Script started on 2023-02-23 08:41:06-08:00
]0;edilin@WWWSTU-P01:~/ceng231/hw2[edilin@WWWSTU-P01 hw2]$ gcc distance.c -Wall -ansi - [Ko distance
]0;edilin@WWWSTU-P01:~/ceng231/hw2[edilin@WWWSTU-P01 hw2]$ ./distance
Please enter two distance values m1, y1, f1, i1, m2, y2, f2, and i2. 
i1: 25
f1: 14 3
y1: 1680
m1: 30
Distance 1 is 30 miles, 1685 yards, 0 feet, 1 inches.
i2: 13
f2: 35
y2: 3650
m2: 45
Distance 2 is 47 miles, 142 yards, 0 feet, 1 inches.
The sum of the distances is 78 miles, 67 yards, 0 feet, and 2 inches.
]0;edilin@WWWSTU-P01:~/ceng231/hw2[edilin@WWWSTU-P01 hw2]$ exit
exit

Script done on 2023-02-23 08:42:57-08:00
